project_id = "ualtuoghgruwxefqynfg"

[functions.create-payfast-payment]
verify_jwt = false

[functions.create-payfast-membership]
verify_jwt = false

[functions.payfast-webhook]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.admin-data]
verify_jwt = false
